# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160824_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_text',
            new_name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
