# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160824_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='likes',
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default=None),
        ),
    ]
